version: '3.8'

services:
  app:
    build: .
    container_name: goauthboiler
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - PORT=8080
      - V1_PREFIX=/api/v1
      - PG_DB_HOST=postgres
      - PG_DB_USER=postgres
      - PG_DB_PASSWORD=postgres
      - PG_DB_NAME=goauthboiler
      - PG_DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-secret-key
      - JWT_ACCESS_EXPIRATION=15m
      - JWT_REFRESH_EXPIRATION=1h
      - MAIL_HOST=smtp.example.com
      - MAIL_PORT=587
      - MAIL_USERNAME=user
      - MAIL_PASSWORD=pass
    networks:
      - goauthboiler-network

  postgres:
    image: postgres:15-alpine
    container_name: goauthboiler-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=goauthboiler
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: goauthboiler-redis
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis-data:/data
    networks:
      - goauthboiler-network

volumes:
  redis-data:

networks:
  goauthboiler-network:
    driver: bridge