server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Go uygulama logları
  - job_name: goauthboiler
    static_configs:
      - targets:
          - localhost
        labels:
          job: goauthboiler
          app: goauthboiler
          env: production
          __path__: /var/log/app.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
            method: method
            path: path
            status: status
            latency: latency
            ip: ip
      - labels:
          level:
          method:
          path:
          status:
      - timestamp:
          source: time
          format: RFC3339Nano

  # PostgreSQL logları
  - job_name: postgres
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          __path__: /var/log/postgresql/*.log

  # Redis logları
  - job_name: redis
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          __path__: /var/log/redis/*.log