server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: goauthboiler
    static_configs:
    - targets:
        - localhost
      labels:
        job: goauthboiler
        app: auth
        __path__: /var/log/goauthboiler/*.log
    pipeline_stages:
    - json:
        expressions:
          level: level
          msg: msg
          time: time
    - labels:
        level:
        msg:
    - timestamp:
        source: time
        format: RFC3339

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["goauthboiler"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            time: time
      - labels:
          level:
      - timestamp:
          source: time
          format: RFC3339
